version: "3.9"

services:
  react-app:
    image: r-art-js-image       
    container_name: r-art-js-container  
    build:
      context: .                
      dockerfile: Dockerfile    
    ports:
      - "3000:3000"             
    volumes:
      - .:/app                  
      - /app/node_modules       
    stdin_open: true            
    tty: true                   
